services:
  web:
    build:
      context: .
      dockerfile: compose/local/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file:
      - .env.local
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: compose/local/web/Dockerfile
    command: celery -A core worker -l INFO
    volumes:
      - ./src:/app
    env_file:
      - .env.local
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.local

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  redis:
    image: redis:latest

volumes:
  postgres_data: